[package]
name = "ui"
version = "0.2.2"
edition = "2024"
repository="https://github.com/JPricey/santorini-ai"

[dependencies]
santorini_core = { path = "../santorini_core" }
eframe = "0.32.1"

[build-dependencies]
winres = "0.1"
